version: "2.2"
services:
  mongo:
    image: mongo:3.4
    container_name: mongo
    ports:
    - 27017:27017
    restart: always
  tc:
    build: .
    container_name: tc
    ports:
    - 0.0.0.0:8000:8000
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017